spring:
  application:
    name: nacos_demo
#  datasource:
#    url: jdbc:mysql://localhost:3306/demo
#    username: root
#    password:
#    driver-class-name: com.mysql.jdbc.Driver
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
    username: root
    password:

  cloud:
    nacos:
      discovery:
        #指定nacos server的地址
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848

server:
  port: 8080

logging:
  config: classpath:logback-dev.xml
